# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: Default
  demands:
  - agent.name -equals master-node

variables:
  - name: bkRg
    value: 'tfstateRG01'
  - name: bkstorage
    value: 'tfstate0126626'
  - name: bkcontainer
    value: 'tfstate'
  - name: bkstoragekey
    value: 'terraform.dev.tfstate'
  - group: terraform-dev-vars

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'allo devops subscription(142f34ee-c9b1-4610-b888-8fee69adccd6)'
              backendAzureRmStorageAccountName: 'tfstate0126626'
              backendAzureRmContainerName: 'pipetfstate'
              backendAzureRmKey: 'dev.tfstate'
          - task: TerraformTask@5
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'AsianFoodServiceConnection'
              backendAzureRmResourceGroupName: '$(bkRg)'
              backendAzureRmStorageAccountName: '$(bkRg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstoragekey)'
          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-var="env=$(env)"'
              environmentServiceNameAzureRM: 'AsianFoodServiceConnection'
          - task: TerraformTask@5
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-var="env=$(env)"'
              environmentServiceNameAzureRM: 'AsianFoodServiceConnection'